base_link:
  link:
    name: base_link
    mesh_properties:
      visual: package://maelstrom_description/model/meshes/maelstromColored.dae
      collision: package://maelstrom_description/model/meshes/collision.stl
    dummy_link:
      name: base_inertia
    dummy_joint:
      name: base_joint
    inertial:
      mass: 38.5 #40.85
      com: 0 0 0
      inertia:
        ixx: 1.32
        ixy: 0.0
        ixz: 0.0
        iyy: 2.84
        iyz: 0.0
        izz: 3.65
    hydro:
      box: # Bounding Box
        length: 0.89
        width: 0.5
        height: 0.33
      cob: 0.024 0.005 0.027 #0.02 0 0.03 # 0.02 0 0.03 # Relative to base_joint?
      volume: 0.0420
      damping:
        linear: -17.0 -50.0 -50.0 -4 -9 -9 #-17.0 -44.0 -44.0 -5 -10 -10
        quadratic: -180.0 -460.0 -460.0 -12 -24.0 -24.0 #-171.0 -444.0 -440.0 -10 -20.0 -20.0
      added_mass: >
        0 0 0 0 0 0
        0 0 0 0 0 0
        0 0 0 0 0 0 
        0 0 0 0 0 0
        0 0 0 0 0 0
        0 0 0 0 0 0
